import React, { useState } from "react";

/**
 * HedgingSuggestions
 *
 * Displays AI-generated hedging suggestions at two levels:
 *   1. Per-position hedges (only for negative-sentiment / overvalued tickers)
 *   2. Portfolio-level recommendations
 *
 * Input signal: DistilBERT sentiment scores.
 * Suggestion text: generated by GPT-4o.
 *
 * Props:
 *   hedgingSuggestions — hedging_suggestions dict from the API response
 */
export default function HedgingSuggestions({ hedgingSuggestions }) {
  const [isHovered, setIsHovered] = useState(false);

  if (!hedgingSuggestions) return null;

  const { ticker_hedges = [], portfolio_recommendations = [], error } = hedgingSuggestions;

  // Show a subtle unavailable state only when both sections are empty / errored
  const isUnavailable =
    error &&
    ticker_hedges.length === 0 &&
    portfolio_recommendations.length === 1 &&
    portfolio_recommendations[0].toLowerCase().includes("unable");

  // Positive confirmation: data present, no error, no hedges needed
  const isAllClear = !error && ticker_hedges.length === 0;

  return (
    <section
      className="rounded-lg p-6 animate-fade-in-up transition-all duration-200 ease-in-out"
      style={{
        background: isHovered ? "rgba(40,60,100,0.95)" : "#131e38",
        borderTop: "4px solid #F59E0B",
        borderRight: isHovered ? "1px solid rgba(255,255,255,0.25)" : "1px solid rgba(71,85,105,0.5)",
        borderBottom: isHovered ? "1px solid rgba(255,255,255,0.25)" : "1px solid rgba(71,85,105,0.5)",
        borderLeft: isHovered ? "1px solid rgba(255,255,255,0.25)" : "1px solid rgba(71,85,105,0.5)",
        boxShadow: isHovered
          ? "0 8px 32px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.15)"
          : "0 1px 3px rgba(0,0,0,0.3)",
        transform: isHovered ? "translateY(-2px)" : "translateY(0)",
      }}
      aria-label="Hedging suggestions"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="mb-5">
        <h2 className="font-semibold text-slate-100 text-lg tracking-tight mb-1">
          🛡️ Hedging Suggestions
        </h2>
        <p className="text-xs text-slate-500 italic">
          AI-generated suggestions based on portfolio risk signals. Not financial advice.
        </p>
      </div>

      {/* ── Unavailable state ───────────────────────────────────────────── */}
      {isUnavailable ? (
        <p className="text-sm text-slate-600 italic">Hedging analysis unavailable.</p>
      ) : isAllClear ? (
        /* ── All-clear positive state ────────────────────────────────────── */
        <div className="py-2">
          <p className="text-sm text-slate-300/90 mb-2">
            ✅ No hedging action needed. Portfolio sentiment and valuations look healthy
            across all positions.
          </p>
          <p className="text-xs text-slate-500 italic">
            Argus will flag hedging opportunities when risk signals are detected.
          </p>
        </div>
      ) : (
        <>
          {/* ── Section 1: Per-ticker hedges ──────────────────────────── */}
          {ticker_hedges.length > 0 && (
            <div className="mb-6">
              <h3
                className="text-xs font-semibold uppercase tracking-wider mb-4"
                style={{ color: "#F59E0B" }}
              >
                Position-Level Hedges
              </h3>

              <div className="space-y-0">
                {ticker_hedges.map((item, i) => (
                  <div key={item.ticker}>
                    <div className="py-3">
                      {/* Ticker + arrow + instrument */}
                      <div className="flex items-center gap-2 mb-1.5 flex-wrap">
                        <span className="mono text-xs text-slate-400/70 bg-slate-700/50 border border-slate-600/40 rounded-full px-2.5 py-0.5 shrink-0">
                          {item.ticker}
                        </span>
                        <span className="text-slate-500 text-xs">→</span>
                        <span className="text-sm font-semibold text-slate-100">
                          {item.hedge_instrument}
                        </span>
                      </div>
                      {/* Explanation */}
                      <p className="text-xs text-slate-400/80 leading-relaxed pl-1">
                        {item.explanation}
                      </p>
                    </div>

                    {/* Divider between items, not after the last */}
                    {i < ticker_hedges.length - 1 && (
                      <div style={{ borderTop: "1px solid rgba(71,85,105,0.3)" }} />
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ── Section 2: Portfolio recommendations ─────────────────── */}
          {portfolio_recommendations.length > 0 && (
            <div>
              <h3
                className="text-xs font-semibold uppercase tracking-wider mb-3"
                style={{ color: "#F59E0B" }}
              >
                Portfolio-Level Recommendations
              </h3>

              <ul className="space-y-2">
                {portfolio_recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-sm text-slate-300/90">
                    <span
                      className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full"
                      style={{ background: "#F59E0B" }}
                      aria-hidden="true"
                    />
                    <span className="leading-relaxed">{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}

      {/* ── Disclaimer ─────────────────────────────────────────────────── */}
      <p
        className="mt-5 text-slate-500/50 italic border-t border-slate-700/40 pt-4"
        style={{ fontSize: "0.75rem", lineHeight: "1.6" }}
      >
        Hedging suggestions are AI-generated for informational purposes only and do not
        constitute financial advice. Consult a qualified advisor before acting on any suggestion.
      </p>
    </section>
  );
}
