import React from "react";

/**
 * Sentiment badge — same threshold logic as TickerCard, slightly larger for summary.
 */
function SentimentBadge({ score }) {
  let className = "badge-neutral";
  let label = "Neutral";

  if (score > 0.2) {
    className = "badge-positive";
    label = "Positive";
  } else if (score < -0.2) {
    className = "badge-negative";
    label = "Negative";
  }

  return (
    <span className={`${className} text-sm px-3 py-1`}>
      {label}&nbsp;
      <span className="opacity-80">
        ({score >= 0 ? "+" : ""}{score.toFixed(3)})
      </span>
    </span>
  );
}

/**
 * Horizontal -1 to +1 sentiment gauge.
 * Track: 12px tall gradient (red → amber → green).
 * Indicator: 20px amber circle with white border.
 * Labels are rendered below the track.
 */
function SentimentGauge({ score }) {
  // Map score [-1, 1] to position [0%, 100%]
  const pct = ((score + 1) / 2) * 100;

  return (
    <div>
      {/* Track */}
      <div
        className="relative w-full rounded-full"
        style={{
          height: "12px",
          background: "linear-gradient(to right, #b91c1c, #F59E0B, #10b981)",
        }}
      >
        {/* Indicator needle — amber circle, white border */}
        <div
          className="absolute top-1/2 -translate-y-1/2 rounded-full"
          style={{
            width: "20px",
            height: "20px",
            background: "#F59E0B",
            border: "2px solid white",
            boxShadow: "0 0 6px rgba(245,158,11,0.5)",
            left: `calc(${pct}% - 10px)`,
            transition: "left 0.7s ease",
          }}
        />
      </div>

      {/* Labels below the track */}
      <div className="flex justify-between text-xs text-slate-500/70 mono mt-2">
        <span>Bearish −1.0</span>
        <span>Neutral 0.0</span>
        <span>Bullish +1.0</span>
      </div>
    </div>
  );
}

/**
 * RiskSummary
 *
 * Portfolio-level summary card — full width, distinct amber top border.
 * Visually separated from individual TickerCards with a lighter background
 * and a 4px top amber accent stripe.
 *
 * Props:
 *   summary          — portfolio_summary string from the API
 *   overallSentiment — overall_sentiment float from the API
 */
export default function RiskSummary({ summary, overallSentiment }) {
  return (
    <section
      className="rounded-lg p-6 animate-fade-in-up"
      style={{
        background: "#131e38",      // slightly lighter than navy-800 for visual separation
        borderTop: "4px solid #F59E0B",
        borderRight: "1px solid rgba(71,85,105,0.5)",
        borderBottom: "1px solid rgba(71,85,105,0.5)",
        borderLeft: "1px solid rgba(71,85,105,0.5)",
        boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
      }}
      aria-label="Portfolio risk summary"
    >
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="font-semibold text-slate-100 text-lg tracking-tight">
          Portfolio Summary
        </h2>
        <SentimentBadge score={overallSentiment} />
      </div>

      {/* ── Sentiment gauge ─────────────────────────────────────────────── */}
      <div className="mb-7">
        <SentimentGauge score={overallSentiment} />
      </div>

      {/* ── Prose summary ───────────────────────────────────────────────── */}
      <p
        className="text-slate-300/90"
        style={{ fontSize: "1rem", lineHeight: "1.7" }}
      >
        {summary}
      </p>

      {/* ── Disclaimer — italic, separated ──────────────────────────────── */}
      <p
        className="mt-5 text-slate-500/50 italic border-t border-slate-700/40 pt-4"
        style={{ fontSize: "0.75rem", lineHeight: "1.6" }}
      >
        This analysis is generated by AI and is for informational purposes only.
        It does not constitute financial advice. Always consult a qualified financial advisor
        before making investment decisions.
      </p>
    </section>
  );
}
